var Backbone = require('backbone');

/* use BCP 47 language tags as the key for each language http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry */

module.exports = Backbone.Model.extend({
  defaults: {
    languages: [
      {
        langName: "English",
        langCode: "en",
        /* Use capitalized keys for widely reused text that must be capitalized */
        Next: "Next",
        IAgree: "I Agree",
        Back: "Back",
        EnterMessage: "Enter message...",
        Skip: "Skip",
        Done: "Done",
        Cancel: "Cancel",
        Close: "Close",
        Yes: "Yes",
        No: "No",
        of: "of",
        Sell: "Sell",
        New: "New",
        Excellent: "Excellent",
        Good: "Good",
        Poor: "Poor",
        SKU: "SKU",
        Refurbished: "Refurbished",
        Physical: "Physical",
        Digital: "Digital",
        Service: "Service",
        Visit: "View Page",
        Item: "Item",
        Items: "Items",
        Stores: "Stores",
        Follow: "Follow",
        Feed: "Feed",
        FeedPlaceholder: "A feed of updates from all of the pages you follow",
        Unfollow: "Unfollow",
        About: "About",
        NoDescriptionAdded: "No description added",
        CoverPhoto: "Cover Photo",
        AboutEmpty: "About is blank...",
        Followers: "Followers",
        Following: "Following",
        Message: "Message",
        Store: "Store",
        Edit: "Edit",
        Used: "Used",
        Delete: "Delete",
        DontDelete: "Don't Delete",
        ConfirmDelete: "Confirm Delete",
        Website: "Website",
        Guid: "OpenBazaar ID (GUID)",
        Welcome: "Welcome",
        CreateStore: "Become a Store",
        GoToMyPage: "My Page",
        SearchForItemsPlaceholder: "Search by name or keyword",
        SearchForPagesPlaceholder: "Search by name or keyword",
        SearchFeedPlaceholder: "Search by handle or GUID",
        SearchForFollowersPlaceholder: "Search by handle or GUID",
        SearchForUsersPlaceholder: "Search by handle or GUID",
        EstDeliveryDomesticPlaceholder: "3-5 Business Days",
        EstDeliveryInternationalPlaceholder: "7-15 Business Days",
        OrderProcessingTimePlaceholder: "Enter time needed to process order",
        TermsAndConditionsPlaceholder: "Enter terms and conditions...",
        TitlePlaceholder: "Enter title",
        DescriptionPlaceholder: "Enter description...",
        ReturnPolicyPlaceholder: "Enter return policy...",
        CategoryPlaceholder: "Enter category",
        CategoryHelperText: "Categories are used to group and organize items within your store.",
        KeywordsHelperText: "Setting keywords helps your item to be discovered in the market.",
        ExpirationDateHelperText: "Set a date for the item to automatically be pulled from your store.",
        ClearExpirationDate: "Clear Expiration Date",
        ReturnPolicy: "Return Policy",
        TermsAndConditions: "Terms and Conditions",
        Photos: "Photos",
        Added: "Added",
        Categorization: "Categorization",
        Expiration: "Expiration",
        Search: "Search",
        Email: "Email",
        Facebook: "Facebook",
        Instagram: "Instagram",
        Twitter: "Twitter",
        Snapchat: "Snapchat",
        BUYNOW: "Buy Now",
        Description: "Description",
        Reviews: "Reviews",
        Shipping: "Shipping",
        Addresses: "Addresses",
        NewAddress: "New Address",
        CurrentAddress: "Current Addresses",
        Returns: "Returns",
        ReturnsPolicy: "Returns Policy",
        Ampersand: "&",
        Keywords: "Keywords",
        ShipsFrom: "Ships From",
        ShipsTo: "Ships To",
        Optional: "Optional",
        Customize: "Customize",
        Save: "Save",
        Changes: "Changes",
        SaveChanges: "Save Changes",
        YourName: "Your name",
        BitcoinReturnAddress: "Bitcoin address",
        LocalCurrency: "Local currency",
        TimeZone: "Time zone",
        ShipToName: "Name",
        ShipToStreet: "Street",
        ShipToCity: "City",
        ShipToState: "State/Province/Region",
        ShipToPostalCode: "Postal code",
        PostalCode: "Postal code",
        ShipToCountry: "Country",
        EnableNotifications: "Enable notifications",
        EnableSSL: "Enable SSL",
        LibbitcoinServerAddress: "Libbitcoin server address",
        ServerIPPort: "Server IP:Port",
        All: "All",
        Name: "Name",
        Price: "Price",
        Available: "Available",
        Keywords: "Keywords",
        Type: "Type",
        Condition: "Condition",
        NSFW: "18+ (Adult content)",
        Local: "Local",
        Domestic: "Domestic",
        Location: "Location",
        International: "International",
        Time: "Time",
        Free: "Free",
        Category: "Category",
        ProcessingTime: "Processing Time",
        UploadPhotos: "Upload photos",
        DragOrUploadPhotos: "Drag or upload photos",
        ExpirationDate: "Expires On",
        UploadCoverPhoto: "Upload a cover photo",
        ShortDescription: "Short Description",
        UpTo140Characters: "Up to 140 Characters",
        PrimaryColor: "Primary Color",
        SecondaryColor: "Secondary Color",
        TextColor: "Text Color",
        CoverPhotoButton: "Select Cover Photo",
        AboutPlaceholder: "Full description",
        BackgroundColor: "Background Color",
        NotificationFollow: "is now following you",
        NoNotifications: "No notifications",
        WelcomeToYourPage: "Welcome to your page!",
        SearchForCategory: "Search for category",
        Moderators: "Moderators",
        CurrentModerators: "Current Moderators",
        AddModerators: "Add New Moderators",
        DeselectToRemoveModerator: "Deselect the moderators you want to remove",
        SelectToAddModerator: "Select the moderators you want to add",
        Categories: "Categories",
        UpTo3: "Up to 3",
        AboutYourStore: "A description of your store",
        PaymentType: "Payment Type",
        ShipTo: "Ship To",
        FreeShipping: "Free Shipping",
        OrderDetails: "Order Details",
        OrderSummary: "Order Summary",
        AllListings: "All Listings",
        ComingSoon: "Coming Soon",
        PaymentPending: "Payment Pending",
        FinalizePurchase: "Finalize Purchase",
        LoadingImage: "Loading Image...",
        UploadAvatar: "Upload Avatar",
        SaveAvatar: "Save Avatar",
        NewAvatar: "Select New Avatar",
        NewCoverImage: "Select New Cover Image",
        errorMessages: {
          saveError: "Data could not be saved.",
          getError: "Data could not be retrieved.",
          missingError: "Some fields are missing or incorrect.",
          serverError: "An incorrect reply was received from the server.",
          userError: "Information for this ID could not be found",
          userNotFoundError: "This person's information is not available. They may have gone offline.",
          notFoundError: "Data could not be loaded for:",
          socketError: "URL for WebSocket failed. Connecting to socket with default address of ws://localhost:18466",
          contractError: "This Item Cannot be Purchased",
          sellerError: "The seller's server has rejected the purchase request"
        },
        saveMessages: {
          Saved: "Saved",
          SaveSuccess: "Your changes have been saved."
        },
        filters: {
          pagesAllTypes: "All types",
          pagesStores: "Stores",
          pagesMods: "Moderator services",
          pagesBasic: "Basic users",
          listingsCurated: "From stores I follow",
          listingsAll: "From all stores"
        },
        nav: {
          searchPlaceholder: "Enter handle or search",
          myPage: "My Page",
          customizePage:"Customize Page",
          sellItem:"New",
          createListing:"New Listing",
          purchases:"Purchases",
          sales:"Sales",
          cases:"Cases",
          notifications:"Notifications",
          settings:"Settings",
          about:"About OpenBazaar",
          support:"Support OpenBazaar"
        },
        onboarding: {
          intro: "OpenBazaar Configuration",
          theme: "Select a Theme for your Page",
          chooseLanguage: "Select Your Language",
          contributors: "%{smart_count} Contributor |||| %{smart_count} Contributors",
          configure: "Configure your experience",
          disclaimer_title: "Disclaimer",
          disclaimer_body: "OpenBazaar is a network for trading goods and services directly between people - using Bitcoin - without any central organization controlling the platform. This means you are responsible for your own activity on the network.<br /><br />OpenBazaar users are not anonymous by default. Most communications between parties are encrypted, but IP addresses are public and can be associated with activity on the network. Malicious parties could use this information against you; protecting your privacy is your own responsibility.<br /><br />OpenBazaar users must ahdere to the laws in their own legal jurisdiction as well as their conscience. The OpenBazaar developers do not condone - and are not responsible for - any use of the platform for illegal activity.<br /><br />The OpenBazaar community of developers has worked hard to deliver a free platform for trade to the world. But as with any software, bugs will be found. The developers are not responsible for any monetary loss associated with problems in the software.<br /><br />By using OpenBazaar you're responsible for your own actions on the OpenBazaar network.",
          yourCountry: "Select Your Country",
          localCurrency: "Select Your Currency",
          LanguagePlaceholder: "Search for language",
          CountryPlaceholder: "Search for country",
          CurrencyPlaceholder: "Search for currency",
          TimezonePlaceholder: "Search for time zone",
          ShortDescriptionPlaceholder: "Say something interesting... (160 char max)",
          timeZone: "Select Your Time Zone",
          yourDetails: "Set Your Information",
          handle: "Handle",
          knownAs: "You're currently known as:",
          wouldYou: "Would you like to register an easy to remember handle?",
          registerNew: "Register New",
          recommended: "Recommended Pages to Follow",
          connectExisting: "Connect Existing",
          avatar: "Set an Avatar",
          chooseAvatar: "Select Avatar"
        },
        buyFlow: {
          MustAddAddress: "You must add an address to ship to",
          VendorShipsTo: "This vendor ships to these countries",
          DoesNotShipHere: "This vendor does not ship here",
          Send: "Send",
          BTCto: "BTC to",
          OpenAddress: "Open Address in Local Wallet",
          CopyAddress: "Copy Pay Address to Clipboard",
          RefreshPayment: "Refresh Payment Status",
          summaryMsg1: "Your payment has been sent to",
          summaryMsg2: "The expected processing time for this order is",
          summaryMsg3: "You can check the status of your order on your",
          purchasesPage: "purchases page"
        }
      },
      {
        langName: "Espa&ntilde;ol",
        langCode: "sp",
        Next: "Siguiente",
        IAgree: "Estoy de acuerdo",
        Back: "Atr&aacute;s",
        Skip: "Omitir",
        Done: "Hecho",
        Cancel: "Cancelar",
        Close: "",
        Yes: "S&iacute;",
        No: "No",
        of: "de",
        Sell: "Vender",
        New: "Nuevo",
        Excellent: "Excelente",
        Good: "Bueno",
        Poor: "Deteriorado",
        SKU: "SKU",
        Refurbished: "Reformado",
        Physical: "F&iacute;sico",
        Digital: "Digital",
        Service: "Servicio",
        Visit: "Ver p&aacute;gina",
        Item: "Art&iacute;culo",
        Items: "Art&iacute;culos",
        Stores: "Tiendas",
        Follow: "Seguir",
        Feed: "Feed",
        FeedPlaceholder: "RSS pr�ximamente",
        Unfollow: "Dejar de seguir",
        About: "Acerca de",
        NoDescriptionAdded: "No hay descripci&oacute;n a&ntilde;adida",
        AboutEmpty: "Acerca de la secci&oacute;n est&aacute; en blanco ...",
        Followers: "Seguidores",
        Following: "Siguiendo a",
        Message: "Mensaje",
        Store: "Tienda",
        Edit: "Editar",
        Used: "Usado",
        Delete: "Borrar",
        DontDelete: "No Borrar",
        ConfirmDelete: "Confirmar eliminaci&oacute;n",
        Website: "Sitio Web",
        Guid: "OpenBazaar ID (GUID)",
        Welcome: "Bienvenida",
        CreateStore: "Crear Tienda",
        GoToMyPage: "Ir a mi p&aacute;gina",
        SearchForItemsPlaceholder: "B&uacute;squeda de art&iacute;culos",
        SearchForPagesPlaceholder: "B&uacute;squeda por palabra clave",
        SearchFeedPlaceholder: "B&uacute;squeda por nombre o apodo",
        SearchForFollowersPlaceholder: "B&uacute;squeda por nombre o apodo",
        SearchForUsersPlaceholder: "B&uacute;squeda por nombre o apodo",
        EstDeliveryDomestic: "3-5 d&iacute;s h&aacute;biles",
        EstDeliveryInternational: "7-15 d&iacute;s h&aacute;biles",
        TermsAndConditionsPlaceholder: "Introduzca T&eacute;rminos y condiciones...",
        TitlePlaceholder: "Introduzca t&iacute;tulo",
        DescriptionPlaceholder: "Introduzca descripci&ooacute;n",
        ReturnPolicyPlaceholder: "Introduzca pol&iacute;ticas de devoluciones",
        CategoryPlaceholder: "Introduzca categor&iacute;a",
        CategoryHelperText: "Las categor&iacute;as se utilizan para agrupar y organizar art&iacute;culos dentro de su tienda.",
        KeywordsHelperText: "Poner palabras claves ayuda a que sus art&iacute;culos sean encontrados en el mercado.",
        ExpirationDateHelperText : "Establecer una fecha para que el art&iacute;culo autom&aacute;ticamente ser&aacute; retirado de su tienda.",
        ClearExpirationDate : "Fecha de Vencimiento Clara",
        ReturnPolicy: "Pol&iacute;tica de devoluciones",
        TermsAndConditions: "T&eacute;rminos y Condiciones",
        Photos: "Fotos",
        Added: "Agregado",
        Categorization: "Categorizaci&oacute;n",
        Expiration: "Expiraci&oacute;n",
        Search: "Buscar",
        Email: "Correo electr&oacute;nico",
        Facebook: "Facebook",
        Instagram: "Instagram",
        Twitter: "Twitter",
        Snapchat: "Snapchat",
        BUYNOW: "COMPRA AHORA",
        Description: "Descripci&oacute;n",
        Reviews: "Cr&iacute;ticas",
        Shipping: "Envío",
        Addresses: "Direcciones",
        CurrentAddress: "Direcciones actuales",
        Returns: "Devoluciones",
        ReturnsPolicy: "Pol&iacute;tica de devoluciones",
        Ampersand: "y",
        ShipsFrom: "Ships From",
        ShipsTo: "Realiza env&iacute;os a",
        Optional: "",
        Customize: "Personalizar",
        Save: "Guardar",
        Changes: "Cambios",
        All: "Todo",
        Name: "Nombre",
        Price: "Precio",
        Available: "Disponible",
        Keywords: "Palabras claves",
        Type: "Tipo",
        Condition: "Condici&oacute;n",
        NSFW: "18+ (contenido para adultos)",
        Local: "Local",
        Domestic: "Interno",
        Location: "Localizaci&oacute;n",
        International: "Internacional",
        Time: "Hora",
        Free: "Gratis",
        Category: "Categor&iacute;a",
        ProcessingTime: "Tiempo de procesamiento",
        UploadPhotos: "Subir fotos",
        DragOrUploadPhotos: "Arrastre o subir fotos",
        UploadCoverPhoto: "Sube una foto de portada",
        ExpirationDate: "Fecha de caducidad",
        ShortDescription: "Breve descripcion",
        UpTo140Characters: "Hasta 140 caracteres",
        PrimaryColor : "Color primario",
        SecondaryColor : "Color secundario",
        TextColor : "Color del texto",
        BackgroundColor : "Color de fondo",
        WelcomeToYourPage: "La bienvenida a su p&aacute;gina",
        SearchForCategory: "B&uacute;squeda de categor&iacute;a",
        Moderators: "Moderadores",
        CurrentModerators: "Moderadores Actuales",
        AddModerators: "Add New Moderadores",
        DeselectToRemoveModerator: "Desactive los moderadores que desea eliminar",
        SelectToAddModerator: "Seleccionar los moderadores que desee agregar",
        Categories: "Categor&iacute;as",
        UpTo3: "Hasta 3",
        PaymentType: "Tipo de pago",
        ShipTo: "Nave",
        FreeShipping: "",
        OrderDetails: "Detalles Orden",
        OrderSummary : " Resumen Orden",
        AboutYourStore: "Una descripci&oacute;n de su tienda",
        NewAddress: "Nueva direcci&oacute;n",
        AllListings: "Todos los listados",
        ComingSoon: "Pr&oacute;ximamente",
        SaveChanges: "Guardar Cambios",
        YourNombre: "Su nombre",
        BitcoinReturnAddress: "Direcci&oacute;n de devoluciones Bitcoin",
        LocalCurrency: "Moneda local",
        TimeZone: "Zona horaria",
        ShipToName: "Env&iacute;r a nombre de",
        ShipToStreet: "Env&iacute;r a la calle",
        ShipToCity: "Env&iacute;r a la ciudad",
        ShipToState: "Env&iacute;r al estado/Provincia/Regi&oacute;n",
        ShipToPostalCode: "Env&iacute;r al c&oacute;digo postal",
        PostalCode: "C&oacute;digo postal",
        ShipToCountry: "Env&iacute;r a pa&iacute;s",
        EnableNotifications: "Activar notificaciones",
        EnableSSL: "Habilitar SSL",
        LibbitcoinServerAddress: "Direcci�n del servidor Libbitcoin",
        ServerIPPort: "Server IP : Puerto",
        PaymentPending: "En espera del pago",
        FinalizePurchase: "Finalizar Compra",
        LoadingImage: "Cargando Imagen ... ",
        UploadAvatar: "Subir Avatar ",
        SaveAvatar: "Guardar Avatar ",
        NewAvatar: "Seleccione Nuevo Avatar",
        NewCoverImage: "Seleccione Nueva Imagen de la Cubierta",
        errorMessages: {
          saveError: "Los datos no se pudieron guardar.",
          getError: "Los datos no se pudieron recuperar.",
          missingError: "Algunos campos faltan o est&aacute;n incorrectos.",
          serverError: "Una respuesta incorrecta se recibi&oacute; desde el servidor.",
          userError: "La informaci&oacute;n para este ID no se pudo encontrar",
          userNotFoundError: "La informaci&oacute;n de esta persona no est&aacute; disponible. Es posible que se hayan desconectado.",
          notFoundError: "Los datos no se pudieron cargar para:",
          socketError: "La URL del WebSocket fall&oacute;. Conectando a socket con la direcci&oacute;n por defecto de ws://localhost:18466",
          contractError: "Este artículo no puede ser comprado" ,
          sellerError: "El servidor del vendedor ha rechazado la solicitud de compra"
        },
        saveMessages: {
          Saved: "Salvado",
          SaveSuccess: "Se han guardado los cambios."
        },
        filters: {
          pagesAllTypes: "Todos los tipos",
          pagesStores: "Tiendas",
          pagesMods: "Servicios de moderadores",
          pagesBasic: "Usuarios b&aacute;sicos",
          listingsCurated: "De tiendas que sigo",
          listingsAll: "De dodas las tiendas"
        },
        nav: {
          searchPlaceholder: "Introduzca un apodo o una palabra clave",
          myPage: "Mi p&aacute;gina",
          customizePage:"Personalizar P&aacute;gina",
          sellItem:"Nuevo",
          createListing:"Nuevo Listado",
          purchases:"Compras",
          sales:"Ventas",
          cases:"Casos",
          notifications:"Notificaciones",
          settings:"Ajustes",
          about:"Acerca de OpenBazaar",
          support:"Soporte OpenBazaar"
        },
        onboarding: {
          intro: "Personalice Su OpenBazaar",
          theme: "El tema de la p&aacute;gina",
          chooseLanguage: "Elige tu idioma",
          contributors: "%{smart_count} Colaboradores |||| %{smart_count} Colaboradores",
          configure: "Configure su Experiencia",
          disclaimer_title: "Nota Legal",
          disclaimer_body: "OpenBazaar es una red para el intercambio de bienes y servicios directamente entre la gente - utilizando Bitcoin - sin ninguna organizaci&oacute;n central que controle la plataforma. Esto quiere decir que eres responsable por tus propias actividades dentro de la red.<br /><br />Los usuarios de OpenBazaar NO SON ANONIMOS por defecto. La mayor&iacute;a de las comunicaciones entre las partes son encriptadas, pero las direcciones IP son p&uacute;blicas y pueden ser asociadas con la actividad en la red. Entes maliciosos pudieran utilizar esta informaci&oacute;n en tu contra; el proteger tu privacidad es tu propia responsabilidad.<br /><br >Los usuarios de OpenBazaar deben apegarse a las leyes de su propia jurisdicci&oacute;n legal tambi&eacute;n as&iacute; como tambien su conciencia. Los desarrolladores de OpenBazaar no condonan - y no son responsables de - ning&uacute;n uso de la plataforma para actividades ilegales.<br /><br />La comunidad de desarrolladores de OpenBazaar ha trabajado duro en entregar una plataforma libre para el comercio internacional. Pero como en todo software, errores ser&aacute;n encontrados. Los desarrolladores no son responsables por ninguna perdida monetaria asociada a los problemas con el software.<br /><br />Al utilizar OpenBazaar Ud. es responsable de sus propias acciones en la red OpenBazaar.",
          yourCountry: "Tu pa&iacute;s",
          localCurrency: "Moneda Local",
          LanguagePlaceholder: "Buscar por idioma",
          CountryPlaceholder: "Buscar por pa&iacute;s",
          CurrencyPlaceholder: "Buscar por moneda",
          TimezonePlaceholder: "Seleccione su zona horaria",
          timeZone: "Zona Horaria",
          yourDetails: "Establecer su informaci&oacute;n",
          handle: "Apodo",
          knownAs: "A Ud. se le conoce como:",
          wouldYou: "Desea registrar un apodo f&aacute;cil de recordar?",
          registerNew: "Registrar Nuevo",
          recommended: "P&aacute;ginas Recomendadas a Seguir",
          connectExisting: "Conectar Existente",
          avatar: "Establecer un Avatar",
          chooseAvatar: "Seleccione avatar"
        },
        buyFlow: {
          MustAddAddress: "Usted debe agregar una dirección para enviar a",
          VendorShipsTo: "este proveedor buques a estos países",
          DoesNotShipHere: "This vendor does not ship here", //notTranslated
          Send: "Semd", //notTranslated
          BTCto: "BTC to", //notTranslated
          OpenAddress: "Open Address in Local Wallet", //notTranslated
          CopyAddress: "Copy Pay Address to Clipboard", //notTranslated
          RefreshPayment: "Refresh Payment Status", //notTranslated
          summaryMsg1: "Your payment has been sent to", //notTranslated
          summaryMsg2: "The expected processing time for this order is", //notTranslated
          summaryMsg3: "You can check the status of your order on your", //notTranslated
          purchasesPage: "purchases page" //notTranslated
        }
      },
      {
        langName: "German",
        langCode: "de",
        /* Use capitalized keys for widely reused text that must be capitalized */
        Next: "Weiter",
        IAgree: "Ich akzeptiere",
        Back: "Zur&uuml;ck",
        Skip: "&Uuml;berspringen",
        Done: "Fertig",
        Cancel: "Abbrechen",
        Yes: "Ja",
        No: "Nein",
        of: "von",
        Sell: "Verkaufen",
        New: "Neu",
        Excellent: "Exzellent",
        Good: "Gut",
        Poor: "Mangelhaft",
        SKU: "SKU",
        Refurbished: "&Uuml;berholt",
        Physical: "Physisch",
        Digital: "Digital",
        Service: "Dienstleistung",
        Item: "Gegenstand",
        Items: "Gegenst&auml;nde",
        Stores: "L&auml;den",
        Follow: "Folgen",
        Feed: "Feed",
        FeedPlaceholder: "Ein Feed von Updates von allen Seiten, die du folgst",
        Unfollow: "Entfolgen",
        About: "&Uuml;ber",
        AboutEmpty: "'&Uuml;ber' ist leer...",
        Followers: "Followers",
        Following: "Folgt",
        Message: 'Nachricht',
        Store: "Store",
        Edit: "Editieren",
        Used: "Benutzt",
        Delete: "L&ouml;schen",
        DontDelete: "Nicht l&ouml;schen",
        ConfirmDelete: "L&ouml;schen Best&auml;tigen",
        Website: "Webseite",
        Guid: "OpenBazaar ID (GUID)",
        Welcome: "Willkommen",
        CreateStore: "Werde ein Verk&auml;ufer",
        GoToMyPage: "Zur eigenen Seite",
        SearchForItemsPlaceholder: "Nach Name oder Schlagwort suchen",
        SearchForPagesPlaceholder: "Nach Name oder Schlagwort suchen",
        SearchFeedPlaceholder: "Nach Name oder Handle suchen",
        SearchForFollowersPlaceholder: "Nach Name oder Handle suchen",
        SearchForUsersPlaceholder: "Nach Name oder Handle suchen",
        EstDeliveryDomesticPlaceholder: "3-5 Werktage",
        EstDeliveryInternationalPlaceholder: "7-15 Werktage",
        OrderProcessingTimePlaceholder: "1-2 Werktage",
        TermsAndConditionsPlaceholder: "Gesch&auml;ftsbedingungen eingeben...",
        TitlePlaceholder: "Titel eingeben",
        DescriptionPlaceholder: "Beschreibung eingeben...",
        ReturnPolicyPlaceholder: "R&uuml;ckgabebedingungen eingeben...",
        CategoryPlaceholder: "Kategorie eingeben",
        CategoryHelperText: "Kategorien werden benutzt um Gegenst&auml;nde in deinem Laden zu gruppieren und organisieren",
        KeywordsHelperText: "Stichw&ouml;rter zu setzen, hilft deinen Gegenstand im Markt zu finden.",
        ExpirationDateHelperText: "Setze ein Datum, an dem dein Gegenstand automatisch gel&ouml;scht werden soll.",
        ClearExpirationDate: "L&ouml;sche das Verfalldatum",
        ReturnPolicy: "R&uuml;cknahmebedingungen",
        TermsAndConditions: "Gesch&auml;ftsbedingungen",
        Photos: "Fotos",
        Added: "Hinzugef&uuml;gt",
        Categorization: "Kategorisierung",
        Expiration: "Verfall",
        Search: "Suchen",
        Email: "Email",
        Facebook: "Facebook",
        Instagram: "Instagram",
        Twitter: "Twitter",
        Snapchat: "Snapchat",
        BUYNOW: "JETZT KAUFEN",
        Description: "Beschreibung",
        Reviews: "Rezensionen",
        Shipping: "Versand",
        Addresses: "Adressen",
        NewAddress : "Neue Adresse",
        CurrentAddress : "Aktuelle Adressen",
        Returns: "R&uuml;ckgabe",
        ReturnsPolicy: "R&uuml;cknahmebedingungen",
        Ampersand: "&",
        Keywords: "",
        ShipsFrom: "Versand von",
        ShipsTo: "Versand nach",
        Optional: "Optional",
        Customize: "Anpassen",
        Save: "Speichern",
        Changes: "&Auml;nderungen",
        SaveChanges: "&Auml;nderungen speichern",
        YourName: "Dein Name",
        BitcoinReturnAddress: "Bitcoin R&uuml;cksendeaddresse",
        LocalCurrency: "Lokale W&auml;hrung",
        TimeZone: "Zeitzone",
        ShipToName: "Versand an Name",
        ShipToStreet: "Versand nach Straße",
        ShipToCity: "Versand nach Stadt",
        ShipToState: "Versand nach Bundesland/Landkreis/Region",
        ShipToPostalCode: "Versand nach Postleitzahl",
        PostalCode: "Postleitzahl",
        ShipToCountry: "Versand nach Land",
        EnableNotifications: "Benachrichtungen aktivieren",
        EnableSSL: "SSL aktivieren",
        LibbitcoinServerAddress: "Libbitcoin Server Addresse",
        ServerIPPort: "Server IP:Port",
        All: "Alle",
        Name: "Name",
        Price: "Preis",
        Available: "Verf&uuml;gbar",
        Keywords: "Schlagwort",
        Type: "Typ",
        Condition: "Beschaffenheit",
        NSFW: "18+ (nicht jugendfreie Inhalte)",
        Local: "Lokal",
        Domestic: "Inland",
        Location: "Standort",
        International: "International",
        Time: "Zeit",
        Free: "Kostenlos",
        Category: "Kategorie",
        ProcessingTime: "Bearbeitungszeit",
        UploadPhotos: "Fotos hochladen",
        DragOrUploadPhotos: "Zieh oder lad Fotos hoch",
        ExpirationDate: "L&auml;uft ab an ",
        UploadCoverPhoto: "Coverbild hochladen",
        ShortDescription: "Kurzbeschreibung",
        UpTo140Characters: "Bis zu 140 Zeichen",
        PrimaryColor: "Prim&auml;rfarbe",
        SecondaryColor: "Sekond&auml;rfarbe",
        TextColor: "Textfarbe",
        BackgroundColor: "Hintergrundfarbe",
        NotificationFollow: "folgt dir nun.",
        NoNotifications: "Keine Benachrichtigungen",
        SearchForCategory: "Nach Kategorie suchen",
        Moderators: "Moderator",
        CurrentModerators: "Aktuelle Moderatoren",
        AddModerators: "Neuen Moderator hinzufügen",
        DeselectToRemoveModerator: "Moderatoren abw&auml;hlen, welche Sie entfernen wollen.",
        SelectToAddModerator: "Moderatoren ausw&auml;hlen, welche Sie hinzufügen wollen.",
        Categories: "Kategorien",
        UpTo3: "Bis zu 3",
        AboutYourStore: "Eine Beschreibung deines Ladens",
        AllListings: "Alle Eintr&auml;ge",
        ComingSoon: "Demn&auml;chst verf&uuml;gbar",
        LoadingImage: "Bild wird geladen...",
        UploadAvatar: "Avatar hochladen",
        SaveAvatar: "Avatar speichern",
        NewAvatar: "W&auml;hlen Sie New Avatar",
        NewCoverImage: "W&auml;hlen Sie New Cover Image",
        errorMessages: {
          saveError: "Daten konnten nicht gespeichert werden.",
          getError: "Daten konnten nicht empfangen werden.",
          missingError: "Einige Felder fehlen oder sind fehlerhaft.",
          serverError: "Eine falsche R&uuml;ckmeldung wurde von dem Server empfangen.",
          userError: "Informationen f&uuml;r diese ID konnten nicht gefunden werden",
          userNotFoundError: "Die Informationen dieser Person sind nicht verf&uuml;gbar. M&ouml;glicherweise ist sie offline gegangen.",
          notFoundError: "Daten konnten nicht geladen werden f&uuml;r:",
          socketError: "URL f&uuml;r den Websocket ist fehlgschlagen. Verbindung mit der Standard-Addresse ws://localhost:18466 wird aufgebaut.",
          contractError: "Dieser Artikel kann nicht gekauft werden",
          sellerError: "Server des Verkäufers die Kaufanfrage abgelehnt wurde"
        },
        saveMessages: {
          Saved: "Gespeichert",
          SaveSuccess: "Ihre &Auml;nderungen wurden gespeichert."
        },
        filters: {
          pagesAllTypes: "Alle Arten",
          pagesStores: "L&auml;den",
          pagesMods: "Moderator Services",
          pagesBasic: "Einfacher Benutzer",
          listingsCurated: "Von L&auml;den, welchen ich folge",
          listingsAll: "Von allen L&auml;den"
        },
        nav: {
          searchPlaceholder: "Handle eingeben oder suchen",
          myPage: "Meine Seite",
          customizePage:"Seite anpassen",
          sellItem:"Neu",
          createListing:"Neuer Eintrag",
          purchases:"Eink&auml;ufe",
          sales:"Verk&auml;ufe",
          cases:"F&auml;lle",
          notifications:"Benachrichtigungen",
          settings:"Einstellungen",
          about:"&Uuml;ber OpenBazaar",
          support:"OpenBazaar unterst&uuml;tzen"
        },
        onboarding: {
          intro: "OpenBazaar Konfiguration",
          theme: "W&auml;hle ein Theme f&uuml;r deine Seite",
          chooseLanguage: "W&auml;hle deine Sprache",
          contributors: "%{smart_count} Mitwirkeder |||| %{smart_count} Mitwirkende",
          configure: "Konfiguriere dein Erlebnis",
          disclaimer_title: "Ausschlussklausel",
          disclaimer_body: "OpenBazaar ist ein Netzwerk um Gegenst&auml;nde und Dienstleistungen zwischen Menschen zu handeln - mit Bitcoin - ohne eine zentrale Organisation, welche die Platform kontrolliert. Dies heißt, dass du verantwortlich f&uuml;r deine Aktivit&auml;t im Netzwerk bist.<br /><br />OpenBazaar Benutzer sind nicht automatisch anonym. Die meiste Kommunikation zwischen Teilnehmern ist verschl&uuml;sselt, aber IP Addressen sind &ouml;ffentlich und k&ouml;nnen mit Aktivit&auml;t auf dem Netzwerk verbunden werden. B&ouml;sartige Teilnehmer k&ouml;nnten diese Information gegen dich verwenden; deine Privatsp&auml;hre zu sch&uuml;tzen ist deine eigene Verantwortung.<br /><br />OpenBazaar Benutzer m&uuml;ssen das Gesetz sowie ihr eigenes Gewissen befolgen - und sind nicht verantwortlich f&uuml;r - jegliche Nutzung der Plattform f&uuml;r illegale Aktivit&auml;ten.<br /><br />Die OpenBazar Community von Entwicklern hat hart gearbeitet, um eine freie Plattform f&uuml;r Handel in der Welt zu schaffen. Aber so wie mit jeder Software, Bugs werden gefunden werden. Die Entwickler sind nicht verantwortlich f&uuml;r jeglichen finanziellen Verlust verbunden mit Problemen in der Software.<br /><br />Indem du OpenBazaar benutzt, bist du verantwortlich f&uuml;r deine Aktionen auf dem OpenBazaar Netzwerk.",
          yourCountry: "W&auml;hle dein Land",
          localCurrency: "W&auml;hle deine W&auml;hrung",
          LanguagePlaceholder: "Suche nach Sprache",
          CountryPlaceholder: "Suche nach Land",
          CurrencyPlaceholder: "Suche nach W&auml;hrung",
          TimezonePlaceholder: "Suche nach Zeitzone",
          timeZone: "W&auml;hle deine Zeitzone",
          yourDetails: "Setze deine Information",
          handle: "Handle",
          knownAs: "Du bist derzeit bekannt als:",
          wouldYou: "Willst du dir einen leicht zu merkenden Handle registrieren?",
          registerNew: "Neu registrieren",
          recommended: "Empfohlene Seiten zu Folgen",
          connectExisting: "Verbinde existierenden",
          avatar: "Setze einen Avatar",
          chooseAvatar: "W&auml;hle einen Avatar"
        },
        buyFlow: {
          MustAddAddress: "Sie m&uuml;ssen eine Adresse zu versenden hinzuzuf&uuml;gen",
          VendorShipsTo: "dieses Anbieters Schiffe in diese L&auml;nde",
          DoesNotShipHere: "This vendor does not ship here", //notTranslated
          Send: "Semd", //notTranslated
          BTCto: "BTC to", //notTranslated
          OpenAddress: "Open Address in Local Wallet", //notTranslated
          CopyAddress: "Copy Pay Address to Clipboard", //notTranslated
          RefreshPayment: "Refresh Payment Status", //notTranslated
          summaryMsg1: "Your payment has been sent to", //notTranslated
          summaryMsg2: "The expected processing time for this order is", //notTranslated
          summaryMsg3: "You can check the status of your order on your", //notTranslated
          purchasesPage: "purchases page" //notTranslated
        }
      },
      {
        langName: "Italiano",
        langCode: "it",
        /* Use capitalized keys for widely reused text that must be capitalized */
        Next: "Avanti",
        IAgree: "Sono d'accordo",
        Back: "Indietro",
        EnterMessage: "Inserire messaggio...",
        Skip: "Salta",
        Done: "Finito",
        Cancel: "Annulla",
        Yes: "Si",
        No: "No",
        of: "di",
        Sell: "Vendere",
        New: "Nuovo",
        Excellent: "Eccellente",
        Good: "Buono",
        Poor: "Scarso",
        SKU: "SKU",
        Refurbished: "Ricondizionato",
        Physical: "Fisico",
        Digital: "Digitale",
        Service: "Servizio",
        Visit: "Visualizza pagina",
        Item: "Oggetto",
        Items: "Oggetti",
        Stores: "Negozi",
        Follow: "Segui",
        Feed: "Feed",
        FeedPlaceholder: "Un feed di aggiornamenti da tutte le pagine che segui",
        Unfollow: "Smetti di seguire",
        About: "About",
        NoDescriptionAdded: "Nessuna descrizione aggiunta",
        CoverPhoto: "Foto di copertina",
        AboutEmpty: "L'about &egrave; vuoto...",
        Followers: "Seguaci",
        Following: "Segue",
        Message: "Messaggio",
        Store: "Negozio",
        Edit: "Modifica",
        Used: "Usato",
        Delete: "Cancella",
        DontDelete: "Non eliminare",
        ConfirmDelete: "Conferma cancellazione",
        Website: "Sito web",
        Guid: "OpenBazaar ID (GUID)",
        Welcome: "Benvenuto",
        CreateStore: "Diventa un negozio",
        GoToMyPage: "Vai alla mia pagina",
        SearchForItemsPlaceholder: "Cerca per nome o parola chiave",
        SearchForPagesPlaceholder: "Cerca per nome o parola chiave",
        SearchFeedPlaceholder: "Cerca per nickname o guid",
        SearchForFollowersPlaceholder: "Cerca per nickname o guid",
        SearchForUsersPlaceholder: "Cerca per nickname o guid",
        EstDeliveryDomesticPlaceholder: "3-5 giorni di lavoro",
        EstDeliveryInternationalPlaceholder: "7-15 giorni di lavoro",
        OrderProcessingTimePlaceholder: "1-2 giorni di lavoro",
        TermsAndConditionsPlaceholder: "Inserire termini e condizioni...",
        TitlePlaceholder: "Inserire titolo",
        DescriptionPlaceholder: "Inserire descrizione...",
        ReturnPolicyPlaceholder: "Inserire politiche di restituazione...",
        CategoryPlaceholder: "Inserire categoria",
        CategoryHelperText: "Le categorie sono usate per raggruppare e organizzare gli oggetti nel tuo negozio.",
        KeywordsHelperText: "Impostare delle parole chiave aiuta i tuoi oggetti ad essere trovari sul mercato.",
        ExpirationDateHelperText: "Imposta una data per l'oggetto per far si che venga tolto automaticamente dal tuo negozio.",
        ClearExpirationDate: "Cancella data di scadenza",
        ReturnPolicy: "Politica di restituzione",
        TermsAndConditions: "Termini e condizioni",
        Photos: "Foto",
        Added: "Aggiunto",
        Categorization: "Categorizzazione",
        Expiration: "Scadenza",
        Search: "Ricerca",
        Email: "Email",
        Facebook: "Facebook",
        Instagram: "Instagram",
        Twitter: "Twitter",
        Snapchat: "Snapchat",
        BUYNOW: "COMPRA ORA",
        Description: "Descrizione",
        Reviews: "Recensioni",
        Shipping: "Spedizione",
        Addresses: "Indirizzi",
        NewAddress: "Nuovo indirizzo",
        CurrentAddress: "Indirizzo attuale",
        Returns: "Restituzione",
        ReturnsPolicy: "Politica di restituzione",
        Ampersand: "&",
        ShipsFrom: "Inviato da",
        ShipsTo: "Inviato verso",
        Optional: "Facoltativo",
        Customize: "Personalizza",
        Save: "Salva",
        Changes: "Modifiche",
        SaveChanges: "Salva modifiche",
        YourName: "Tuo nome",
        BitcoinReturnAddress: "Indirizzo Bitcoin di restituzione",
        LocalCurrency: "Moneta locale",
        TimeZone: "Fuso orario",
        ShipToName: "Invia a nominativo",
        ShipToStreet: "Invia all'indirizzo",
        ShipToCity: "Invia alla citt&agrave;",
        ShipToState: "Invia alla Stato/Provincia/Regione",
        ShipToPostalCode: "Invia al codice postale",
        PostalCode: "Codice postale",
        ShipToCountry: "Invia alla nazione",
        EnableNotifications: "Abilita notifiche",
        EnableSSL: "Abilita SSL",
        LibbitcoinServerAddress: "Indirizzo del server Libbitcoin",
        ServerIPPort: "Server IP:Port",
        All: "Tutti",
        Name: "Nome",
        Price: "Prezzo",
        Available: "Disponibile",
        Keywords: "Parole chiave",
        Type: "Tipo",
        Condition: "Condizione",
        NSFW: "18+ (Adult content)?",
        Local: "Locale",
        Domestic: "Nazionale",
        Location: "Locazione",
        International: "Internazionale",
        Time: "Tempo",
        Free: "Gratuito",
        Category: "Categoria",
        ProcessingTime: "Tempo di preparazione",
        UploadPhotos: "Caricare foto",
        DragOrUploadPhotos: "Trascina o carica foto",
        ExpirationDate: "Scadenza per il",
        UploadCoverPhoto: "Upload a cover photo",
        ShortDescription: "Breve descrizione",
        UpTo140Characters: "Fino a 140 caratteri",
        PrimaryColor: "Colore principale",
        SecondaryColor: "Colore secondario",
        TextColor: "Colore testo",
        CoverPhotoButton: "Seleziona foto di copertina",
        AboutPlaceholder: "Descrizione completa",
        BackgroundColor: "Colore di sfondo",
        NotificationFollow: "ora ti sta seguendo",
        NoNotifications: "Nessuna notifica",
        WelcomeToYourPage: "Benvenuto alla tua pagina!",
        SearchForCategory: "Cerca per categoria",
        Moderators: "Moderatori",
        CurrentModerators: "Moderatori Correnti",
        AddModerators: "Aggiungere Nuovi Moderatori",
        DeselectToRemoveModerator: "Deselezionare i moderatori che si desidera rimuovere",
        SelectToAddModerator: "Selezionare i moderatori che si desidera aggiungere",
        Categories: "Categorie",
        UpTo3: "Fino a 3",
        AboutYourStore: "Una descrizione del tuo negozio",
        PaymentType: "Tipo di pagamento",
        ShipTo: "Invia a",
        OrderDetails: "Dettaglio ordine",
        OrderSummary: "Riepilogo ordine",
        AllListings: "Tutti gli annunci",
        ComingSoon: "In arrivo",
        PaymentPending: "Pagamento in sospeso",
        FinalizePurchase: "Finalizza acquisto",
        LoadingImage: "Caricamento immagine...",
        UploadAvatar: "Carica Avatar",
        SaveAvatar: "Salva Avatar",
        NewAvatar: "Selezionare Nuovo Avatar",
        NewCoverImage: "Selezionare Nuovo Copertina",
        errorMessages: {
          saveError: "I dati non sono stati salvati.",
          getError: "I dati non sono stati recuperati.",
          missingError: "Alcuni campi sono mancanti o non corretti.",
          serverError: "E' stata ricevuta dal server una risposta non corretta.",
          userError: "Non &egrave; stato possibile trovare le informazioni di questo ID.",
          userNotFoundError: "Le informazioni di questa persona non sono disponibili. Potrebbero essere scollegati.",
          notFoundError: "I dati non sono stati caricati per:",
          socketError: "Connessione all'URL per WebSocket fallita. Connettere al socket con l'indirizzo di default ws://localhost:18466",
          contractError: "Questo articolo non pu&ograve; essere acquistato",
          sellerError: "Il server del venditore ha respinto la richiesta di acquisto"
        },
        saveMessages: {
          Saved: "Salvato",
          SaveSuccess: "Le modifiche sono state salvate."
        },
        filters: {
          pagesAllTypes: "Tutti i tipi",
          pagesStores: "Negozi",
          pagesMods: "Servizi di moderazione",
          pagesBasic: "Utenti normali",
          listingsCurated: "Dai negozi che seguo",
          listingsAll: "Da tutti i negozi"
        },
        nav: {
          searchPlaceholder: "Inserisci nickname o cerca",
          myPage: "La mia pagina",
          customizePage:"Personalizza pagina",
          sellItem:"Nuovo",
          createListing:"Crea elenco",
          purchases:"Acquisti",
          sales:"Vendite",
          cases:"Cause",
          notifications:"Notifiche",
          settings:"Impostazioni",
          about:"About OpenBazaar",
          support:"Supporto OpenBazaar"
        },
        onboarding: {
          intro: "Configurazione OpenBazaar",
          theme: "Seleziona un Tema per la tua pagina",
          chooseLanguage: "Seleziona la tua lingua",
          contributors: "%{smart_count} Contributore |||| %{smart_count} Contributori",
          configure: "Imposta la tua esperienza",
          disclaimer_title: "Disclaimer",
          disclaimer_body: "OpenBazaar &egrave; un network per scambi di beni e servizi direttamente fra le persone - usando Bitcoin - senza nessuna organizzazione centrale che controlli la piattaforma. Questo significa che tu sei responsabile per le tue attività sul network.<br /><br />Gli utenti di OpenBazaar non sono anonimi di default. La maggior parte delle comunicazioni fra le parti sono cifrate, ma gli indirizzi IP sono pubblici e possono essere associati con le attivit&agrave; sul network. Parti malevole potrebbero utilizzare queste informazioni contro di voi; proteggere la tua privay è una tua responsabilit&agrave;.<br /><br />Gli utenti di OpenBazaar devono rispettare le leggi nella propria giurisdizione legale cos&igrave; come la loro coscienza. Gli sviluppatori di OpenBazaar non perdonano - e non sono responsabili - per alcun uso illegale della piattaforma.<br /><br />La comunit&agrave; deglo sviluppatori di OpenBazaar ha lavorato duramente per fornire una piattaforma libera per il commercio nel mondo. Ma come per ogni software, si troveranno bug. Gli sviluppatori non sono responsabili per alcuna perdita monetaria associata a problemi nel software.<br /><br />Usando OpenBazaar sei responsabile per le tue azioni sul network OpenBazaar.",
          yourCountry: "Seleziona il tuo paese",
          localCurrency: "Seleziona la tua moneta",
          LanguagePlaceholder: "Seleziona la tua lingua",
          CountryPlaceholder: "Cerca per paese",
          CurrencyPlaceholder: "Cerca per moneta",
          TimezonePlaceholder: "Cerca per fuso orario",
          ShortDescriptionPlaceholder: "Di qualcosa di interessante... (massimo 160 caratteri)",
          timeZone: "Seleziona il tuo fuso orario",
          yourDetails: "Imposta le tue informazioni",
          handle: "Nickname",
          knownAs: "Sei conosciuto come:",
          wouldYou: "Ti andrebbe di registrare un nickname facile da ricordare?",
          registerNew: "Registra nuovo",
          recommended: "Pagine raccomandate di seguire",
          connectExisting: "Collega ad esistente",
          avatar: "Imposta un Avatar",
          chooseAvatar: "Seleziona Avatar"
        },
        buyFlow: {
          MustAddAddress: "&Egrave; necessario aggiungere un indirizzo da spedire ai",
          VendorShipsTo: "Questo fornitore navi a questi paesi",
          DoesNotShipHere: "This vendor does not ship here", //notTranslated
          Send: "Semd", //notTranslated
          BTCto: "BTC to", //notTranslated
          OpenAddress: "Open Address in Local Wallet", //notTranslated
          CopyAddress: "Copy Pay Address to Clipboard", //notTranslated
          RefreshPayment: "Refresh Payment Status", //notTranslated
          summaryMsg1: "Your payment has been sent to", //notTranslated
          summaryMsg2: "The expected processing time for this order is", //notTranslated
          summaryMsg3: "You can check the status of your order on your", //notTranslated
          purchasesPage: "purchases page" //notTranslated
        }
      },
      {
        langName: "French",
        langCode: "fr",
        /* Use capitalized keys for widely reused text that must be capitalized */
        Next: "Suivant",
        IAgree: "Je suis d'accord",
        Back: "Retour",
        Skip: "Passer",
        Done: "Termin&eacute;",
        Cancel: "Annuler",
        Yes: "Oui",
        No: "Non",
        of: "de",
        Sell: "Vendre",
        New: "Nouveau",
        Excellent: "Excellent",
        Good: "Bon",
        Poor: "M&eacute;diocre",
        SKU: "SKU",
        Refurbished: "Remis &agrave; neuf",
        Physical: "Physique",
        Digital: "Num&eacute;rique",
        Service: "Service",
        Visit: "Voir Page",
        Item: "Article",
        Items: "Articles",
        Stores: "Boutiques",
        Follow: "Suivre",
        Feed: "Flux",
        FeedPlaceholder: "Un flux de mises &agrave; jour de toutes les pages que vous suivez",
        Unfollow: "Ne plus suivre",
        About: "&agrave; propos",
        NoDescriptionAdded: "Aucune description ajout&eacute;e",
        CoverPhoto: "Photo de couverture",
        AboutEmpty: "&agrave; propos est vide...",
        Followers: "Abonn&eacute;s",
        Following: "Abonnements",
        Message: "Message",
        Store: "Boutique",
        Edit: "Editer",
        Used: "Utilis&eacute;",
        Delete: "Supprimer",
        DontDelete: "Ne pas supprimer",
        ConfirmDelete: "Confirmer la suppression",
        Website: "Site web",
        Guid: "OpenBazaar ID (GUID)",
        Welcome: "Bienvenue",
        CreateStore: "Cr&eacute;er une boutique",
        GoToMyPage: "Ma page",
        SearchForItemsPlaceholder: "Rechercher par nom ou par mot-cl&eacute;",
        SearchForPagesPlaceholder: "Rechercher par nom ou par mot-cl&eacute;",
        SearchFeedPlaceholder: "Rechercher par nom ou par nom d'utilisateur",
        SearchForFollowersPlaceholder: "Rechercher par nom ou par nom d'utilisateur",
        SearchForUsersPlaceholder: "Rechercher par nom ou par nom d'utilisateur",
        EstDeliveryDomesticPlaceholder: "3-5 Jours Ouvr&eacute;s",
        EstDeliveryInternationalPlaceholder: "7-15 Jours Ouvr&eacute;s",
        OrderProcessingTimePlaceholder: "1-2 Jours Ouvr&eacute;s",
        TermsAndConditionsPlaceholder: "Entrer les termes et conditions...",
        TitlePlaceholder: "Entrer un titre",
        DescriptionPlaceholder: "Entrer une description...",
        ReturnPolicyPlaceholder: "Entrer une condition de retour...",
        CategoryPlaceholder: "Entrer une cat&eacute;gorie",
        CategoryHelperText: "Les cat&eacute;gories sont utilis&eacute;es pour regrouper et organiser les articles au sein de votre boutique.",
        KeywordsHelperText: "D&eacute;finir des mots-cl&eacute;s permet &agrave; votre article d'&ecirc;tre d&eacute;couvert sur le march&eacute;.",
        ExpirationDateHelperText: "D&eacute;finir une date pour que l'article soit automatiquement retir&eacute; de votre boutique.",
        ClearExpirationDate: "Effacer la date d'expiration",
        ReturnPolicy: "Condition de retour",
        TermsAndConditions: "Termes et Conditions",
        Photos: "Photos",
        Added: "Ajout&eacute;",
        Categorization: "Cat&eacute;gorisation",
        Expiration: "Expiration",
        Search: "Rechercher",
        Email: "Email",
        Facebook: "Facebook",
        Instagram: "Instagram",
        Twitter: "Twitter",
        Snapchat: "Snapchat",
        BUYNOW: "ACHETER MAINTENANT",
        Description: "Description",
        Reviews: "Avis",
        Shipping: "Exp&eacute;dition",
        Addresses: "Adresses",
        NewAddress: "Nouvelle adresse",
        CurrentAddress: "Adresse actuelle",
        Returns: "Retours",
        ReturnsPolicy: "Conditions de retours",
        Ampersand: "&",
        ShipsFrom: "Exp&eacute;di&eacute; de",
        ShipsTo: "Envoy&eacute; &agrave;",
        Optional: "Optionnel",
        Customize: "Personnaliser",
        Save: "Sauvegarder",
        Changes: "Changements",
        SaveChanges: "Sauvegarder les changements",
        YourName: "Votre nom",
        BitcoinReturnAddress: "Adresse Bitcoin",
        LocalCurrency: "Devise locale",
        TimeZone: "Fuseau horaire",
        ShipToName: "Nom",
        ShipToStreet: "Rue",
        ShipToCity: "Ville",
        ShipToState: "R&eacute;gion/D&eacute;partement",
        ShipToPostalCode: "Code postal",
        PostalCode: "Code postal",
        ShipToCountry: "Pays",
        EnableNotifications: "Activer les notifications",
        EnableSSL: "Activer SSL",
        LibbitcoinServerAddress: "Adresse de serveur Libbitcoin",
        ServerIPPort: "Serveur IP :Port",
        All: "Tout",
        Name: "Nom",
        Price: "Prix",
        Available: "Disponible",
        Keywords: "Mots-cl&eacute;s",
        Type: "Type",
        Condition: "Condition",
        NSFW: "18+ (Contenu adulte)",
        Local: "Local",
        Domestic: "National",
        Location: "Emplacement",
        International: "International",
        Time: "Heure",
        Free: "Gratuit",
        Category: "Cat&eacute;gorie",
        ProcessingTime: "D&eacute;lai de traitement",
        UploadPhotos: "Uploader des photos",
        DragOrUploadPhotos: "Glisser ou uploader des photos",
        ExpirationDate: "Expire le",
        UploadCoverPhoto: "Uploader une photo de couverture",
        ShortDescription: "Br&egrave;ve description",
        UpTo140Characters: "Jusqu'&agrave; 140 caract&egrave;res",
        PrimaryColor: "Couleur primaire",
        SecondaryColor: "Couleur secondaire",
        TextColor: "Couleur de texte",
        CoverPhotoButton: "S&eacute;lectionner une photo de couverture",
        AboutPlaceholder: "Description compl&egrave;te",
        BackgroundColor: "Couleur de fond",
        NotificationFollow: "vous suit",
        NoNotifications: "Aucune notification",
        WelcomeToYourPage: "Bienvenue sur votre page !",
        SearchForCategory: "Rechercher par cat&eacute;gorie",
        Moderators: "Mod&eacute;rateurs",
        CurrentModerators: "Mod&eacute;rateurs actuels",
        AddModerators: "Ajouter de nouveaux mod&eacute;rateurs",
        DeselectToRemoveModerator: "D&eacute;s&eacute;lectionner les mod&eacute;rateurs que vous voulez supprimer",
        SelectToAddModerator: "S&eacute;lectionner les mod&eacute;rateurs que vous voulez ajouter",
        Categories: "Categories",
        UpTo3: "Jusqu'&agrave; 3",
        AboutYourStore: "Une description de votre boutique",
        PaymentType: "Type de paiement",
        ShipTo: "Envoyer &agrave;",
        OrderDetails: "D&eacute;tails de la commande",
        OrderSummary: "R&eacute;sum&eacute; de la commande",
        AllListings: "Annonces",
        ComingSoon: "&agrave; venir",
        PaymentPending: "Paiement en attente",
        FinalizePurchase: "Finaliser l'achat",
        LoadingImage: "Chargement de l'image...",
        UploadAvatar: "Uploader un Avatar",
        SaveAvatar: "Enregistrer un Avatar",
        NewAvatar: "S&eacute;lectionner un nouvel Avatar",
        NewCoverImage: "S&eacute;lectionner une nouvelle image de couverture",
        errorMessages: {
          saveError: "Impossible de sauvegarder les donn&eacute;es.",
          getError: "Impossible de r&eacute;cup&eacute;rer les donn&eacute;es.",
          missingError: "Certains champs sont incorrects ou manquants.",
          serverError: "Une r&eacute;ponse incorrecte a &eacute;t&eacute; reçue du serveur.",
          userError: "Les informations pour cette ID sont introuvables",
          userNotFoundError: "Les informations de cette personne ne sont pas disponibles. Elles sont peut-&ecirc;tre hors ligne.",
          notFoundError: "Les donn&eacute;es ne peuvent pas &ecirc;tre r&eacute;cup&eacute;r&eacute;es pour :",
          socketError: "L'URL pour WebSocket a &eacute;chou&eacute;. Connexion au socket avec l'adresse par d&eacute;faut de ws://localhost:18466",
          contractError: "Cet article ne peut pas &ecirc;tre achet&eacute;",
          sellerError: "Le serveur du vendeur a rejet&eacute; la demande d'achat"
        },
        saveMessages: {
          Saved: "Saved",
          SaveSuccess: "Vos changements ont &eacute;t&eacute; enregistr&eacute;s."
        },
        filters: {
          pagesAllTypes: "Tous les types",
          pagesStores: "Boutiques",
          pagesMods: "Services de mod&eacute;rateur",
          pagesBasic: "Utilisateurs de base",
          listingsCurated: "Depuis les boutiques que je suis",
          listingsAll: "Depuis toutes les boutiques"
        },
        nav: {
          searchPlaceholder: "Entrer un nom d'utilisateur ou rechercher",
          myPage: "Ma Page",
          customizePage:"Personnaliser la page",
          sellItem:"Nouveau",
          createListing:"Nouvelle annonce",
          purchases:"Achats",
          sales:"Ventes",
          cases:"Cas",
          notifications:"Notifications",
          settings:"Param&egrave;tres",
          about:"&agrave; propos d'OpenBazaar",
          support:"Soutenir OpenBazaar"
        },
        onboarding: {
          intro: "Configuration d'OpenBazaar",
          theme: "S&eacute;lectionnez un th&egrave;me pour votre page",
          chooseLanguage: "S&eacute;lectionnez votre langue",
          contributors: "%{smart_count} Contributeur |||| %{smart_count} Contributeur",
          configure: "Configurez votre exp&eacute;rience",
          disclaimer_title: "Disclaimer",
          disclaimer_body: "OpenBazaar est un r&eacute;seau commercial de biens et services de personne &agrave; personne - utilisant Bitcoin - sans aucune organisation centrale exerçant une autorit&eacute; sur la plate-forme. Cela signifie que vous &ecirc;tes responsable de votre propre activit&eacute; sur le r&eacute;seau. <br /><br />Les utilisateurs d'OpenBazaar ne sont pas anonymes par d&eacute;faut. La plupart des communications entre les partis sont chiffr&eacute;es, mais les adresses IP sont publiques et peuvent &ecirc;tre associ&eacute;es avec une activit&eacute; sur le r&eacute;seau. Des partis malveillants pourraient utiliser ces informations contre vous ; prot&eacute;ger votre vie priv&eacute;e est votre propre responsabilit&eacute;. <br /><br />Les utilisateurs d'OpenBazaar doivent respecter les lois de leur propre juridiction ainsi que leur conscience. Les d&eacute;veloppeurs d'OpenBazaar ne tol&egrave;rent pas - et ne sont pas responsables -  de toute utilisation de la plate-forme pour une activit&eacute; ill&eacute;gale. <br /><br />La communaut&eacute; de d&eacute;veloppeurs d'OpenBazaar a travaill&eacute; dur afin d'offrir une plate-forme libre pour le commerce dans le monde. Mais, comme avec tout logiciel, des bugs seront trouv&eacute;s. Les d&eacute;veloppeurs ne sont pas responsables de toute perte mon&eacute;taire associ&eacute;e &agrave; des probl&egrave;mes dans le logiciel. <br /><br />En utilisant OpenBazaar vous &ecirc;tes responsable de vos propres actions sur le r&eacute;seau OpenBazaar.",
          yourCountry: "S&eacute;lectionnez votre pays",
          localCurrency: "S&eacute;lectionnez votre devise",
          LanguagePlaceholder: "Rechercher par langue",
          CountryPlaceholder: "Rechercher par pays",
          CurrencyPlaceholder: "Rechercher par devise",
          TimezonePlaceholder: "Rechercher par fuseau horaire",
          ShortDescriptionPlaceholder: "Dites quelque chose d'int&eacute;ressant... (160 caract&egrave;res max)",
          timeZone: "S&eacute;lectionner votre fuseau horaire",
          yourDetails: "D&eacute;finir vos informations",
          handle: "Nom d'utilisateur",
          knownAs: "Vous &ecirc;tes actuellement connu comme :",
          wouldYou: "Voulez-vous enregistrer un nom d'utilisateur facilement m&eacute;morisable ?",
          registerNew: "Enregistrer",
          recommended: "Pages recommand&eacute;es &agrave; suivre",
          connectExisting: "Connect Existing",
          avatar: "D&eacute;finir un Avatar",
          chooseAvatar: "S&eacute;lectionner un Avatar"
        },
        buyFlow: {
          MustAddAddress: "Vous devez ajouter une adresse pour exp&eacute;dier",
          VendorShipsTo: "Ce vendeur expédie vers ces pays",
          DoesNotShipHere: "This vendor does not ship here", //notTranslated
          Send: "Semd", //notTranslated
          BTCto: "BTC to", //notTranslated
          OpenAddress: "Open Address in Local Wallet", //notTranslated
          CopyAddress: "Copy Pay Address to Clipboard", //notTranslated
          RefreshPayment: "Refresh Payment Status", //notTranslated
          summaryMsg1: "Your payment has been sent to", //notTranslated
          summaryMsg2: "The expected processing time for this order is", //notTranslated
          summaryMsg3: "You can check the status of your order on your", //notTranslated
          purchasesPage: "purchases page" //notTranslated
        }
      },
      {
        langName: "Română",
        langCode: "ro",
        /* Use capitalized keys for widely reused text that must be capitalized */
        Next: "Următorul",
        IAgree: "Sunt de acord",
        Back: "Înapoi",
        EnterMessage: "Introduceți mesajul...",
        Skip: "Sari peste",
        Done: "Efectuat",
        Cancel: "Anulare",
        Yes: "Da",
        No: "Nu",
        of: "din",
        Sell: "Vânzare",
        New: "Nou",
        Excellent: "Excelent",
        Good: "Bun",
        Poor: "Prost",
        SKU: "SKU",
        Refurbished: "Renovat",
        Physical: "Fizic",
        Digital: "Digital",
        Service: "Serviciu",
        Visit: "Vizualizare pagină",
        Item: "Produs",
        Items: "Produse",
        Stores: "Magazine",
        Follow: "Urmărire",
        Feed: "Feed",
        FeedPlaceholder: "Lista de actualizări de la toate paginile urmărite",
        Unfollow: "Oprire Urmărire",
        About: "Despre",
        NoDescriptionAdded: "Nu a fost adăgată descrirea",
        CoverPhoto: "Fotografie Copertă",
        AboutEmpty: "Despre este gol...",
        Followers: "Urmăritori",
        Following: "Se Urmărește",
        Message: "Mesaj",
        Messages: "Mesaje",
        Store: "Magazin",
        Edit: "Modificare",
        Used: "Folosit",
        Delete: "Ștergere",
        DontDelete: "Nu Ștergeți",
        ConfirmDelete: "Confirmați Ștergerea",
        Website: "Website",
        Guid: "OpenBazaar ID (GUID)",
        Welcome: "Bun Venit",
        CreateStore: "Deveniți un Magazin",
        GoToMyPage: "Pagina Mea",
        SearchForItemsPlaceholder: "Căutare după nume sau cuvânt cheie",
        SearchForPagesPlaceholder: "Căutare după nume sau cuvânt cheie",
        SearchFeedPlaceholder: "Căutare după nume sau GUID",
        SearchForFollowersPlaceholder: "Căutare după nume sau GUID",
        SearchForUsersPlaceholder: "Căutare după nume sau GUID",
        EstDeliveryDomesticPlaceholder: "3-5 Zile Lucrătoare",
        EstDeliveryInternationalPlaceholder: "7-15 Zile Lucrătoare",
        OrderProcessingTimePlaceholder: "1-2 Zile Lucrătoare",
        TermsAndConditionsPlaceholder: "Introduceți termenii și condițiile...",
        TitlePlaceholder: "Introduceți titlul",
        DescriptionPlaceholder: "Introduceți descrierea...",
        ReturnPolicyPlaceholder: "Introduceți politica de returnare...",
        CategoryPlaceholder: "Introduceți categoria",
        CategoryHelperText: "Categoriile sunt folosite pentru gruparea și organizarea produselor în magazinul dvs.",
        KeywordsHelperText: "Setarea cuvintelor cheie ajută produsul dvs. să fie găsit în piaţă",
        ExpirationDateHelperText: "Setați o dată pentru produsul dvs. să fie scos automat din magazin",
        ClearExpirationDate: "Ștergeți Data Expirării",
        ReturnPolicy: "Politica de Returnare",
        TermsAndConditions: "Termeni și Condiții",
        Photos: "Fotografii",
        Added: "Adăugat",
        Categorization: "Categorizare",
        Expiration: "Expirare",
        Search: "Căutare",
        Email: "Email",
        Facebook: "Facebook",
        Instagram: "Instagram",
        Twitter: "Twitter",
        Snapchat: "Snapchat",
        BUYNOW: "CUMPĂRAȚI ACUM",
        Description: "Descriere",
        Reviews: "Recenzii",
        Shipping: "Livrare",
        Addresses: "Adrese",
        NewAddress: "Adresă Nouă",
        CurrentAddress: "Adresele Curente",
        Returns: "Returnări",
        ReturnsPolicy: "Politica de Returnări",
        Ampersand: "&",
        ShipsFrom: "Se Livrează Din",
        ShipsTo: "Se Livrează Spre",
        Optional: "Opțional",
        Customize: "Customizare",
        Save: "Salvare",
        Changes: "Modificări",
        SaveChanges: "Salvare Modificări",
        YourName: "Numele dvs.",
        BitcoinReturnAddress: "Adresa Bitcoin",
        LocalCurrency: "Valuta locală",
        TimeZone: "Fus orar",
        ShipToName: "Numele",
        ShipToStreet: "Strada",
        ShipToCity: "Orașul",
        ShipToState: "Statul/Provincia/Regiunea",
        ShipToPostalCode: "Codul poștal",
        PostalCode: "Cod poștal",
        ShipToCountry: "Țara",
        EnableNotifications: "Activare notificări",
        EnableSSL: "Activare SSL",
        LibbitcoinServerAddress: "Adresa Libbitcoin a serverului",
        ServerIPPort: "Server IP:Port",
        All: "Toate",
        Name: "Nume",
        Price: "Preț",
        Available: "Disponibil",
        Keywords: "Cuvinte cheie",
        Type: "Tip",
        Condition: "Condiție",
        NSFW: "18+ (Conținut pentru adulți)",
        Local: "Local",
        Domestic: "Domestic",
        Location: "Locație",
        International: "Internațional",
        Time: "Timp",
        Free: "Gratis",
        Category: "Categorie",
        ProcessingTime: "Timp de Procesare",
        UploadPhotos: "Încărcare fotografii",
        DragOrUploadPhotos: "Trageți sau încărcați imaginile",
        ExpirationDate: "Expiră Pe",
        UploadCoverPhoto: "Încărcați imaginea copertă",
        ShortDescription: "Descriere Scurtă",
        UpTo140Characters: "Până la 140 de caractere",
        PrimaryColor: "Culoarea Primară",
        SecondaryColor: "Culoarea Secundară",
        TextColor: "Culoarea Textului",
        CoverPhotoButton: "Selectați Fotografia Copertă",
        AboutPlaceholder: "Descrierea completă",
        BackgroundColor: "Culoarea de Fundal",
        NotificationFollow: "acum vă urmărește",
        NoNotifications: "Nu sunt notificări",
        WelcomeToYourPage: "Bun venit pe pagina dvs.!",
        SearchForCategory: "Căutare categorie",
        Moderators: "Moderatori",
        CurrentModerators: "Moderatorii Curenți",
        AddModerators: "Adăugare Moderator Nou",
        DeselectToRemoveModerator: "Deselectați moderatorii pe care doriți să îi ștergeți",
        SelectToAddModerator: "Selectați moderatorii pe care doriți să îi adăugați",
        Categories: "Categorii",
        UpTo3: "Până la 3",
        AboutYourStore: "O descriere pentru magazinul dvs.",
        PaymentType: "Tipul de Plată",
        ShipTo: "Livrare Spre",
        OrderDetails: "Detaliile Comenzii",
        OrderSummary: "Rezumatul Comenzii",
        AllListings: "Listări",
        ComingSoon: "Apare în Curând",
        PaymentPending: "Plata în așteptare",
        FinalizePurchase: "Finalizare Achiziție",
        LoadingImage: "Se Încarcă Imaginea...",
        UploadAvatar: "Încărcare Avatar",
        SaveAvatar: "Salvare Avatar",
        NewAvatar: "Selectare Avatar Nou",
        NewCoverImage: "Selectare Imagine Copertă Nouă",
        errorMessages: {
          saveError: "Datele nu au putut fi salvate.",
          getError: "Datele nu au putut fi primite.",
          missingError: "Câteva câmpuri lipsesc sau sunt încorecte.",
          serverError: "Un răspuns greșit a fost primit de la server.",
          userError: "Informația despre acest ID nu a fost găsită",
          userNotFoundError: "Informația persoanei date nu este disponibilă. Posibil s-a deconectat.",
          notFoundError: "Nu pot fi încarcate datele pentru:",
          socketError: "URL pentru WebSocket a eșuat. Conectarea la socket cu adresa implicită ws://localhost:18466",
          contractError: "Acest Articol Nu Poate Fi Procurat",
          sellerError: "Serverul vânzătorului a respins cererea de cumpărare"
        },
        saveMessages: {
          Saved: "Salvat",
          SaveSuccess: "Modificările dvs. au fost salvate."
        },
        filters: {
          pagesAllTypes: "Toate tipurile",
          pagesStores: "Magazine",
          pagesMods: "Servicii de moderare",
          pagesBasic: "Utilizatori de bază",
          listingsCurated: "Din magazinele urmărite de mine",
          listingsAll: "Din toate magazinele"
        },
        nav: {
          searchPlaceholder: "Introduceți numele sau căutați",
          myPage: "Pagina mea",
          customizePage:"Customizare Pagină",
          sellItem:"Nou",
          createListing:"Listare Nouă",
          purchases:"Cumpărături",
          sales:"Vânzări",
          cases:"Cazuri",
          notifications:"Notificări",
          settings:"Setări",
          about:"Despre OpenBazaar",
          support:"Susținere OpenBazaar"
        },
        onboarding: {
          intro: "Configurare OpenBazaar",
          theme: "Selectați o Temă pentru Pagina dvs.",
          chooseLanguage: "Selectați Limba dvs.",
          contributors: "%{smart_count} Contributor |||| %{smart_count} Contributori",
          configure: "Configurați-vă experiența",
          disclaimer_title: "Act de Declinare a Responsabilităţii",
          disclaimer_body: "OpenBazaar este o rețea pentru comercializarea bunurilor și serviciilor direct între oameni - folosind Bitcoin - fără nici o organizație centrală care ar controla platforma. Aceasta înseamnă ca dvs. sunteți responsibil(ă) pentru activitatea dvs. în rețea.<br /><br />Utilizatorii OpenBazaar nu sunt anonimi implicit. Majoritatea cumunicațiilor între părți sunt criptate, dar adresa IP este publică și poate fi asociată cu activitatea în rețea. Părțile răutăcioase pot folosi această informație împotriva dvs.; protejarea confidențialității este responsabilitatea dvs.<br /><br />Utilizatorii OpenBazaar trebuie să respecte legile în jurisdicția lor legală de asemenea și conștiința lor. Dezvoltatorii OpenBazaar nu scuză - și nu sunt responsabili pentru - orice folosire a platformei în activități ileagale.<br /><br />Comunitatea dezvoltatorilor OpenBazaar a lucrat din greu pentru a livra lumii o platformă gratuită pentru comerț. Dar ca orice soft, bug-uri vor fi găsite. Dezvoltatorii nu sunt responsabili pentru orice pierdere monetară asociată cu problemele din soft.<br /><br />Folosind OpenBazaar sunteți responsabili pentru acțiunile proprii în rețeaua OpenBazaar.",
          yourCountry: "Selectați Țara dvs.",
          localCurrency: "Selectați Valuta dvs.",
          LanguagePlaceholder: "Căutare limbă",
          CountryPlaceholder: "Căutare țară",
          CurrencyPlaceholder: "Căutare valută",
          TimezonePlaceholder: "Căutare fus orar",
          ShortDescriptionPlaceholder: "Spuneți ceva interesant... (160 caractere maxim)",
          timeZone: "Selectați Fusul dvs. Orar",
          yourDetails: "Setați Informația dvs.",
          handle: "Nume",
          knownAs: "La moment sunteți cunoscut ca:",
          wouldYou: "Doriți să înregistrați un nume ușor de reținut?",
          registerNew: "Înregistrați-vă Acum",
          recommended: "Pagini Recomandate pentru Urmărire",
          connectExisting: "Conectare Existente",
          avatar: "Setați un Avatar",
          chooseAvatar: "Selectare Avatar"
        },
        buyFlow: {
          MustAddAddress: "Trebuie să adăugați o adesă pentru livrare",
          VendorShipsTo: "Acest furnizor livrează către următoarele țări",
          DoesNotShipHere: "This vendor does not ship here", //notTranslated
          Send: "Semd", //notTranslated
          BTCto: "BTC to", //notTranslated
          OpenAddress: "Open Address in Local Wallet", //notTranslated
          CopyAddress: "Copy Pay Address to Clipboard", //notTranslated
          RefreshPayment: "Refresh Payment Status", //notTranslated
          summaryMsg1: "Your payment has been sent to", //notTranslated
          summaryMsg2: "The expected processing time for this order is", //notTranslated
          summaryMsg3: "You can check the status of your order on your", //notTranslated
          purchasesPage: "purchases page" //notTranslated
        }
      },
      {
        langName: "Russian",
        langCode: "ru",
        /* Use capitalized keys for widely reused text that must be capitalized */
        Next: "Далее",
        IAgree: "Согласен",
        Back: "Назад",
        EnterMessage: "Ввести сообщение...",
        Skip: "Пропустить",
        Done: "Готово",
        Cancel: "Отмена",
        Yes: "Да",
        No: "Нет",
        of: "из",
        Sell: "Продать",
        New: "Новый",
        Excellent: "Идеальное",
        Good: "Хорошее",
        Poor: "Плохое",
        SKU: "SKU",
        Refurbished: "Восстановленный",
        Physical: "Физический",
        Digital: "Цифровой",
        Service: "Услуга",
        Visit: "Просмотров",
        Item: "Штук",
        Items: "Штук",
        Stores: "Магазинов",
        Follow: "Подписан",
        Feed: "Лента",
        FeedPlaceholder: "Лента обновлений, за которыми я слежу",
        Unfollow: "Отписаться",
        About: "О нас",
        NoDescriptionAdded: "Добавленные описания",
        CoverPhoto: "Обложка",
        AboutEmpty: "Описание не заполнено...",
        Followers: "Читатели",
        Following: "Читаемые",
        Message: "Сообщение",
        Messages: "Сообщений",
        Store: "Магазин",
        Edit: "Редактировать",
        Used: "В употреблении",
        Delete: "Удалить",
        DontDelete: "Не удалять",
        ConfirmDelete: "Да, удалить",
        Website: "Веб-сайт",
        Guid: "OpenBazaar ID (GUID)",
        Welcome: "Welcome",
        CreateStore: "Стать магазином",
        GoToMyPage: "Моя страница",
        SearchForItemsPlaceholder: "Поиск по имени и ключевому слову",
        SearchForPagesPlaceholder: "Поиск по имени и ключевому слову",
        SearchFeedPlaceholder: "Поиск по имени или GUID",
        SearchForFollowersPlaceholder: "Поиск по имени или GUID",
        SearchForUsersPlaceholder: "Поиск по имени или GUID",
        EstDeliveryDomesticPlaceholder: "3-5 рабочих дней",
        EstDeliveryInternationalPlaceholder: "7-15 рабочих дней",
        OrderProcessingTimePlaceholder: "1-2 рабочих дней",
        TermsAndConditionsPlaceholder: "Введите правила и условия...",
        TitlePlaceholder: "Введите название",
        DescriptionPlaceholder: "Введите описание...",
        ReturnPolicyPlaceholder: "Введите условия возврата...",
        CategoryPlaceholder: "Выберите категорию",
        CategoryHelperText: "Категории используются для сортировки выкладки товаров в вашем магазине.",
        KeywordsHelperText: "Указание ключевых слов улучшают позиционирование в поиске.",
        ExpirationDateHelperText: "Выберите дату для снятия с продажи.",
        ClearExpirationDate: "Точная дата для снятия с продажи",
        ReturnPolicy: "Политика возвратов",
        TermsAndConditions: "Правила и условия",
        Photos: "фотографий",
        Added: "добавлено",
        Categorization: "Категоризация",
        Expiration: "Срок действия",
        Search: "Поиск",
        Email: "Email",
        Facebook: "Facebook",
        Instagram: "Instagram",
        Twitter: "Twitter",
        Snapchat: "Snapchat",
        BUYNOW: "Купи сейчас",
        Description: "Описание",
        Reviews: "Отзывы",
        Shipping: "Доставка",
        Addresses: "Адреса",
        NewAddress: "Новый адрес",
        CurrentAddress: "Текущие адреса",
        Returns: "Возвраты",
        ReturnsPolicy: "Политика возвратов",
        Ampersand: "&",
        ShipsFrom: "Доставка из",
        ShipsTo: "Доставка в",
        Optional: "Дополнительно",
        Customize: "Настроиь",
        Save: "Сохранить",
        Changes: "Изменения",
        SaveChanges: "Сохранить изменения",
        YourName: "Ваше имя",
        BitcoinReturnAddress: "Bitcoin адрес",
        LocalCurrency: "Местная валюта",
        TimeZone: "Часовой пояс",
        ShipToName: "Имя",
        ShipToStreet: "Улица",
        ShipToCity: "Город",
        ShipToState: "Страна/Провинция/Город",
        ShipToPostalCode: "Почтовый индекс",
        PostalCode: "Почтовый индекс",
        ShipToCountry: "Страна",
        EnableNotifications: "Включить уведомления",
        EnableSSL: "Включить SSL",
        LibbitcoinServerAddress: "Адрес сервера Libbitcoin",
        ServerIPPort: "Сервер IP:Port",
        All: "Все",
        Name: "Имя",
        Price: "Цена",
        Available: "Доступно",
        Keywords: "Ключевые слова",
        Type: "Тип",
        Condition: "Состояние",
        NSFW: "18+ (для взрослых)",
        Local: "Местный",
        Domestic: "Внутри страны",
        Location: "Местонахождение",
        International: "Международный",
        Time: "Время",
        Free: "Свободный",
        Category: "Категория",
        ProcessingTime: "Время процессинга",
        UploadPhotos: "Загрузить фото",
        DragOrUploadPhotos: "Перетащите или выберите фото",
        ExpirationDate: "Срок действия",
        UploadCoverPhoto: "Загрузите фото",
        ShortDescription: "Короткое описание",
        UpTo140Characters: "До 140 знаков",
        PrimaryColor: "Главный цвет",
        SecondaryColor: "Дополнительный цвет",
        TextColor: "Цвет текста",
        CoverPhotoButton: "Выберите обложку",
        AboutPlaceholder: "Полное описание",
        BackgroundColor: "Фоновый цвет",
        NotificationFollow: "подписан на вас",
        NoNotifications: "Нет уведомлений",
        WelcomeToYourPage: "Добро пожаловать!",
        SearchForCategory: "Поиск категории",
        Moderators: "Модераторы",
        CurrentModerators: "Текущие модераторы",
        AddModerators: "Добавить модераторов",
        DeselectToRemoveModerator: "Выберите модераторов для удаления",
        SelectToAddModerator: "Выберите модераторов для добавления",
        Categories: "Категории",
        UpTo3: "До 3-х",
        AboutYourStore: "Описание магазина",
        PaymentType: "Способ платежа",
        ShipTo: "Доставка",
        OrderDetails: "Подробности заказа",
        OrderSummary: "Сведения заказа",
        AllListings: "Листинги",
        ComingSoon: "Скоро",
        PaymentPending: "Платеж в процессе",
        FinalizePurchase: "Финализировать",
        LoadingImage: "Загрузка...",
        UploadAvatar: "Загрузить аватар",
        SaveAvatar: "Сохранить аватар",
        NewAvatar: "Выбрать аватар",
        NewCoverImage: "Выбрать обложку",
        errorMessages: {
          saveError: "Данные невозможно сохранить.",
          getError: "Данные невозможно получить.",
          missingError: "Поля заполнены неправильно.",
          serverError: "Сервер прислал неправильные запросы.",
          userError: "Информация по этому ID не найдена",
          userNotFoundError: "Человек недоступен. Возможно его нет в сети.",
          notFoundError: "Данные нельзя загрузить для:",
          socketError: "URL для WebSocket недоступен. Подключаемся к адресу по умолчанию ws://localhost:18466",
          contractError: "Этот товар недоступен для продажи",
          sellerError: "Сервер продавца отключил эту возможность"
        },
        saveMessages: {
          Saved: "Сохранено",
          SaveSuccess: "Ваши изменения сохранены."
        },
        filters: {
          pagesAllTypes: "Все типы",
          pagesStores: "Магазины",
          pagesMods: "Сервисы модератора",
          pagesBasic: "Базовые пользователи",
          listingsCurated: "С магазинов по подписке",
          listingsAll: "Со всех магазинов"
        },
        nav: {
          searchPlaceholder: "Введите имя или запрос",
          myPage: "Моя страница",
          customizePage:"Настроить страницу",
          sellItem:"Разместить товар",
          createListing:"Новый листинг",
          purchases:"Покупки",
          sales:"Продажи",
          cases:"История",
          notifications:"Уведомления",
          settings:"Настройки",
          about:"Об OpenBazaar",
          support:"Поддержка OpenBazaar"
        },
        onboarding: {
          intro: "Конфигурация OpenBazaar",
          theme: "Выберите тему для вашей страницы",
          chooseLanguage: "Выберите ваш язык",
          contributors: "%{smart_count} вкладчик |||| %{smart_count} вкладчиков",
          configure: "Настройте рабочее место",
          disclaimer_title: "Дисклеймер",
          disclaimer_body: "OpenBazaar является открытой сетью для прямой торговли с использованием Bitcoin - без какого-либо центрального органа или компании контроллирующего платформу. Это значит что вы ответственны за ваши собственные действия.<br /><br />Пользователи OpenBazaar не являются анонимными по умолчанию. Большинство коммуникаций между сторонами шифруются, но IP адреса публичны, поэтому могут быть ассоциированны с запросами поступающими с них в сеть. Злоумышленники могут использовать эту информацию против вас; защита приватности - в ваших руках.<br /><br />Пользователи OpenBazaar должны соблюдать законы в непосредственной юрисдикции их местонахождения. Разработчики OpenBazaar не могут контроллировать каждое использование - и не несут ответственности за любое использование платформы в незаконных целях.<br /><br />Сообщество OpenBazaar приложило огромное количество усилий по созданию свободной платформы для международной торговли. Как и в любом программном обеспечении, наши программы тоже содержат ошибки. Разработчики не несут ответственности за любые потери связанные с использованием этого программного продукта.<br /><br />Используя OpenBazaar вы несёте полную ответственность за любые действия совершаемые вами в сети OpenBazaar.",
          yourCountry: "Выберите вашу страну",
          localCurrency: "Выберите вашу валюту",
          LanguagePlaceholder: "Вычисление языка",
          CountryPlaceholder: "Вычисление страны",
          CurrencyPlaceholder: "Вычисление валюты",
          TimezonePlaceholder: "Вычисление часового пояса",
          ShortDescriptionPlaceholder: "Расскажите что-нибудь интересное... (160 максимум)",
          timeZone: "Выберите часовой пояс",
          yourDetails: "Задайте информацию",
          handle: "Псевдоним",
          knownAs: "Сейчас ваше имя:",
          wouldYou: "Вы желаете зарегистрировать простой хэндл?",
          registerNew: "Зарегистрировать новый",
          recommended: "Рекомендуемые странички для подписки",
          connectExisting: "Подключить существующий",
          avatar: "Поставить аватарку",
          chooseAvatar: "Выбрать аватарку"
        },
        buyFlow: {
          MustAddAddress: "Вы должны указать адрес для доставки",
          VendorShipsTo: "Этот производитель отправляет в следующие страны",
          DoesNotShipHere: "This vendor does not ship here", //notTranslated
          Send: "Semd", //notTranslated
          BTCto: "BTC to", //notTranslated
          OpenAddress: "Open Address in Local Wallet", //notTranslated
          CopyAddress: "Copy Pay Address to Clipboard", //notTranslated
          RefreshPayment: "Refresh Payment Status", //notTranslated
          summaryMsg1: "Your payment has been sent to", //notTranslated
          summaryMsg2: "The expected processing time for this order is", //notTranslated
          summaryMsg3: "You can check the status of your order on your", //notTranslated
          purchasesPage: "purchases page" //notTranslated
        }
      }
    ]
  }
});
