var Backbone = require('backbone');

/* use BCP 47 language tags as the key for each language http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry */

module.exports = Backbone.Model.extend({
  defaults: {
    languages: [
      {
        langName: "English",
        langCode: "en",
        /* Use capitalized keys for widely reused text that must be capitalized */
        Next: "Next",
        IAgree: "I Agree",
        Back: "Back",
        Skip: "Skip",
        Done: "Done",
        Cancel: "Cancel",
        Yes: "Yes",
        No: "No",
        Sell: "Sell",
        New: "New",
        Excellent: "Excellent",
        Good: "Good",
        Poor: "Poor",
        SKU: "SKU",
        Refurbished: "Refurbished",
        Physical: "Physical",
        Digital: "Digital",
        Service: "Service",
        Item: "Item",
        Items: "Items",
        Stores: "Stores",
        Follow: "Follow",
        Unfollow: "Unfollow",
        About: "About",
        AboutEmpty: "About is blank...",
        Followers: "Followers",
        Following: "Following",
        Message: 'Message',
        Store: "Store",
        Edit: "Edit",
        Used: "Used",
        Delete: "Delete",
        ConfirmDelete: "Confirm Delete",
        Website: "Website",
        Guid: "OpenBazaar ID (GUID)",
        Welcome: "Welcome to OpenBazaar",
        CreateStore: "Become a Store",
        SearchForItemsPlaceholder: "Search for items",
        SearchForFollowersPlaceholder: "Search by name or handle",
        EstDeliveryDomesticPlaceholder: "3-5 Business Days",
        EstDeliveryInternationalPlaceholder: "7-15 Business Days",
        OrderProcessingTimePlaceholder: "1-2 Business Days",
        TermsAndConditionsPlaceholder: "Enter terms and conditions...",
        TitlePlaceholder: "Enter title",
        DescriptionPlaceholder: "Enter description...",
        ReturnPolicyPlaceholder: "Enter return policy...",
        CategoryPlaceholder: "Enter category",
        CategoryHelperText: "Categories are used to group and organize items within your store.",
        KeywordsHelperText: "Setting keywords helps your item to be discovered in the market.",
        ExpirationDateHelperText: "Set a date for the item to automatically be pulled from your store.",
        ClearExpirationDate: "Clear Expiration Date",
        ReturnPolicy: "Return Policy",
        TermsAndConditions: "Terms and Conditions",
        Photos: "Photos",
        Added: "Added",
        Categorization: "Categorization",
        Expiration: "Expiration",
        Search: "Search",
        Email: "Email",
        Facebook: "Facebook",
        Instagram: "Instagram",
        Twitter: "Twitter",
        Snapchat: "Snapchat",
        BUYNOW: "BUY NOW",
        Description: "Description",
        Reviews: "Reviews",
        Shipping: "Shipping",
        Returns: "Returns",
        ReturnsPolicy: "Returns Policy",
        Ampersand: "&",
        ShipsFrom: "Ships From",
        ShipsTo: "Ships To",
        Optional: "Optional",
        Customize: "Customize",
        Save: "Save",
        Changes: "Changes",
        All: "All",
        Name: "Name",
        Price: "Price",
        Available: "Available",
        Keywords: "Keywords",
        Type: "Type",
        Condition: "Condition",
        NSFW: "NSFW",
        Local: "Local",
        Domestic: "Domestic",
        Location: "Location",
        International: "International",
        Time: "Time",
        Free: "Free",
        Category: "Category",
        ProcessingTime: "Processing Time",
        UploadPhotos: "Upload photos",
        DragOrUploadPhotos: "Drag or upload photos",
        ExpirationDate: "Expires On",
        UploadCoverPhoto: "Upload a cover photo",
        ShortDescription: "Short Description",
        UpTo140Characters: "Up to 140 Characters",
        PrimaryColor: "Primary Color",
        SecondaryColor: "Secondary Color",
        TextColor: "Text Color",
        BackgroundColor: "Background Color",
        SearchForCategory: "Search for category",
        Moderators: "Moderators",
        Categories: "Categories",
        UpTo3: "Up to 3",
        AboutYourStore: "A description of your store",
        nav: {
          searchPlaceholder: "Enter handle or search",
          myPage: "My Page",
          customizePage:"Customize Page",
          sellItem:"New Listing",
          createListing:"New Listing",
          purchases:"Purchases",
          sales:"Sales",
          cases:"Cases",
          notifications:"Notifications",
          settings:"Settings",
          about:"About OpenBazaar",
          support:"Support OpenBazaar"
        },
        onboarding: {
          intro: "Personalize Your OpenBazaar",
          theme: "Your Page Theme",
          chooseLanguage: "Choose Your Language",
          contributors: "%{smart_count} Contributor |||| %{smart_count} Contributors",
          configure: "Configure your experience",
          disclaimer_title: "Disclaimer",
          disclaimer_body: "OpenBazaar is a network for trading goods and services directly between people - using Bitcoin - without any central organization controlling the platform. This means you are responsible for your own activity on the network.<br /><br />OpenBazaar users are not anonymous by default. Most communications between parties are encrypted, but IP addresses are public and can be associated with activity on the network. Malicious parties could use this information against you; protecting your privacy is your own responsibility.<br /><br />OpenBazaar users must ahdere to the laws in their own legal jurisdiction as well as their conscience. The OpenBazaar developers do not condone - and are not responsible for - any use of the platform for illegal activity.<br /><br />The OpenBazaar community of developers has worked hard to deliver a free platform for trade to the world. But as with any software, bugs will be found. The developers are not responsible for any monetary loss associated with problems in the software.<br /><br />By using OpenBazaar you're responsible for your own actions on the OpenBazaar network.",
          yourCountry: "Your Country",
          localCurrency: "Currency of Choice",
          LanguagePlaceholder: "Search for a language",
          CountryPlaceholder: "Search for a country",
          CurrencyPlaceholder: "Search for a currency",
          TimezonePlaceholder: "Search for a time zone",
          timeZone: "Time Zone",
          handle: "Handle",
          knownAs: "You're currently known as:",
          wouldYou: "Would you like to register an easy to remember handle?",
          registerNew: "Register New",
          connectExisting: "Connect Existing",
          avatar: "Avatar",
          chooseAvatar: "Choose Avatar"
        }
      },
      {
        langName: "Spanish",
        langCode: "sp",
        /* this is just for reference. It was created by Google translate, and is probably very inaccurate. */
        Next: "en Siguiente",
        IAgree: "Estoy de acuerdo",
        Back: "Atrás",
        Skip: "Omitir",
        Done: "Hecho",
        Cancel: "Cancelar",
        Yes: "Sí",
        No: "No",
        Sell: "vendor",
        New: "Nuevo",
        Excellent: "Excelente",
        Good: "Bueno",
        Poor: "Deteriorado",
        SKU: "SKU",
        Refurbished: "Reformado",
        Physical: "Físico",
        Digital: "Digital",
        Service: "Servicio",
        Item: "Artículo",
        Items: "Artículos",
        Stores: "Tiendas",
        Follow: "Seguir",
        Unfollow: "Dejar de seguir",
        About: "Acerca de",
        AboutEmpty: "Acerca de la sección está en blanco ...",
        Followers: "Seguidores",
        Following: "Después",
        Message: 'Mensaje',
        Store: "Tienda",
        Edit: "Editar",
        Used: "",
        Delete: "Borrar",
        ConfirmDelete: "Confirmar eliminación",
        Website: "Sitio Web",
        Guid: "OpenBazaar ID (GUID)",
        Welcome: "Bienvenida",
        CreateStore: "Crear Tienda",
        SearchForItemsPlaceholder: "",
        SearchForFollowersPlaceholder: "",
        EstDeliveryDomestic: "",
        EstDeliveryInternational: "",
        TermsAndConditionsPlaceholder: "",
        TitlePlaceholder: "",
        DescriptionPlaceholder: "",
        ReturnPolicyPlaceholder: "",
        CategoryPlaceholder: "",
        CategoryHelperText: "",
        KeywordsHelperText: "",
        ExpirationDateHelperText : "Establecer una fecha para que el artículo automáticamente será retirado de su tienda.",
        ClearExpirationDate : "Fecha de Vencimiento Claro",
        ReturnPolicy: "",
        TermsAndConditions: "",
        Photos: "",
        Added: "",
        Search: "",
        Expiration: "",
        Email: "Correo electrónico",
        Facebook: "Facebook",
        Instagram: "Instagram",
        Twitter: "Twitter",
        Snapchat: "Snapchat",
        BUYNOW: "COMPRA AHORA",
        Description: "Descripción",
        Reviews: "Críticas",
        Shipping: "Envío",
        Returns: "Devoluciones",
        ReturnsPolicy: "Política de devoluciones",
        Ampersand: "y",
        ShipsFrom: "Ships From",
        ShipsTo: "Realiza envíos a",
        Optional: "",
        Customize: "Personaliza",
        Save: "Guardar",
        Changes: "Cambios",
        All: "Todo",
        Name: "Nombre",
        Price: "Precio",
        Available: "Disponible",
        Keywords: "Palabras claves",
        Type: "Tipo",
        Condition: "Condición",
        NSFW: "NSFW",
        Local: "Local",
        Domestic: "Interno",
        Location: "Localización",
        International: "Internacional",
        Time: "Hora",
        Free: "Gratis",
        Category: "Categoría",
        ProcessingTime: "Tiempo de procesamiento",
        UploadPhotos: "Subir fotos",
        DragOrUploadPhotos: "Arrastre o subir fotos",
        UploadCoverPhoto: "Sube una foto de portada",
        ExpirationDate: "Fecha de caducidad",
        ShortDescription: "Breve descripcion",
        UpTo140Characters: "Hasta 140 caracteres",
        PrimaryColor : "Color primario",
        SecondaryColor : "Color secundario",
        TextColor : "Color del texto",
        BackgroundColor : "Color de fondo",
        SearchForCategory: "Búsqueda de categoría",
        Moderators: "Moderadores",
        Categories: "Categorías",
        UpTo3: "Hasta 3",
        AboutYourStore: "Una descripción de su tienda",
        nav: {
          searchPlaceholder: "Introduzca un mango o una palabra clave",
          myPage: "Mi página",
          customizePage:"Personalizar Página",
          sellItem:"Venta de artículos",
          purchases:"Las compras",
          sales:"Ventas",
          cases:"Casos",
          notifications:"Notificaciones",
          settings:"Ajustes",
          about:"Acerca OpenBazaar",
          support:"Soporte OpenBazaar"
        },
        onboarding: {
          intro: "Personalice Su OpenBazaar",
          theme: "El tema de la página",
          chooseLanguage: "Elige tu idioma",
          contributors: "%{smart_count} Colaboradores |||| %{smart_count} Colaboradores",
          configure: "Configure su Experiencia",
          disclaimer_title: "Nota Legal",
          disclaimer_body: "disclaimer text",
          yourCountry: "Tu país",
          localCurrency: "Moneda Local",
          LanguagePlaceholder: "",
          CountryPlaceholder: "",
          CurrencyPlaceholder: "",
          TimezonePlaceholder: "",
          timeZone: "Zona Horaria",
          handle: "Apodo",
          knownAs: "Estás conocido como:",
          wouldYou: "¿Quieres registrar una fácil de recordar manejar?",
          registerNew: "Registrar Nuevo",
          connectExisting: "Conecte Existente",
          avatar: "Avatar",
          chooseAvatar: "Elija Avatar"
        }
      }
    ]
  }
});